apiVersion: v1
kind: Service
metadata:
  name: external-database

spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    # No selector! We'll create Endpoints manually

---

apiVersion: v1
kind: Endpoints
metadata:
  name: external-database

subsets:
- addresses:
  - ip: 192.168.1.100  # External database IP
  ports:
  - port: 3306


# Now pods can connect using "external-database" as hostname
