apiVersion: v1
kind: Service
metadata:
  name: multi-port-service


spec:
  selector:
    app: multi-port
  ports:
  - name: http          # Name is REQUIRED for multiple ports
    protocol: TCP
    port: 80
    targetPort: 80

  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
