apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rolling
  labels:
    app: nginx-rolling
    tier: frontend


spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1             # Max extra pods during update
      maxUnavailable: 1       # Max pods that can be unavailable
  selector:
    matchLabels:
      app: nginx-rolling
      tier: frontend

  template:
    metadata:
      labels:
        app: nginx-rolling
        tier: frontend

    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80

