apiVersion: v1
kind: Pod

metadata:
  name: redis


spec:
  containers:
    - name: redis-container
      image: redis:alpine
      ports:
        - containerPort: 6379
      volumeMounts:
        - name: redis-data
          mountPath: /var/lib/redis


  volumes:
    - name: redis-data
      emptyDir: {}