apiVersion: v1
kind: Pod
metadata:
  name: postgresql-pod
  labels:
    app: postgresql
    tier: database


spec:
  containers:
    - name: postgresql-pod
      image: postgres:16
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data/pgdata
  
  volumes:
    - name: postgres-data
      emptyDir: {}