apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  clusterIP: None
  selector:
    app: web
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: web
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      initContainers:
      - name: init-config
        image: busybox
        command:
        - sh
        - -c
        - |
          echo "Initializing pod $(hostname)..."
          echo "Pod: $(hostname)" > /work-dir/index.html
          echo "Time: $(date)" >> /work-dir/index.html
          echo "Ordinal: ${HOSTNAME##*-}" >> /work-dir/index.html
        volumeMounts:
        - name: www
          mountPath: /work-dir
      containers:
      - name: nginx
        image: nginx:1.26
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
    