apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: app
    image: busybox
    command:
    - sh
    - -c
    - |
      echo "USERNAME: $DB_USER"
      echo "PASSWORD: $DB_PASS"
      echo "Database: $DB_NAME"
      sleep 3600
    
    env:
    # Method 1: Reference individual keys
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: username
    
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password
    
    # Method 2: Import all keys as env vars
    envFrom:
    - secretRef:
        name: db-secret