apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_HOST: postgres.default.svc.cluster.local
  DB_PORT: "5432"
  DB_USER: appuser
  DB_PASSWORD: supersecretpassword
  DB_NAME: appdb
