apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 3000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app

spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: node:18-alpine
          command: ["sh", "-c"]
          args:
            - |
              echo "DB_HOST=$DB_HOST";
              echo "DB_PORT=$DB_PORT";
              echo "DB_USER=$DB_USER";
              echo "DB_PASSWORD=$DB_PASSWORD";
              echo "DB_NAME=$DB_NAME";
              node -e "require('http').createServer((_,res)=>res.end('OK')).listen(3000)"
          ports:
          - containerPort: 3000
          volumeMounts:
            - name: db-secret-v2
              mountPath: /etc/db-secret
              readOnly: true
      volumes:
        - name: db-secret-v2
          secret:
            secretName: db-secret-v2