apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-clone
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: postgres-pvc