apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
  - name: writer
    image: busybox
    command:
    - /bin/sh
    - -c
    - |
      echo "Writing data at $(date)" > /data/data.txt
      cat /data/file.txt
      sleep 3600
    volumeMounts:
    - name: data-volume
      mountPath: /data
  
  volumes:
  - name: data-volume
    emptyDir: {} # Empty Directory, lost when pod is deleted
