apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: test
    image: busybox
    command:
    - /bin/sh
    - -c
    - |
      echo "Data from hostpath at $(date)" > /data/file.txt
      cat /data/file.txt
      sleep 3600
    volumeMounts:
    - name: host-volume
      mountPath: /data
  
  volumes:
  - name: host-volume
    hostPath:
      path: /mnt/data  # Directory on the node
      type: DirectoryOrCreate