apiVersion: v1
kind: Pod
metadata:
  name: writer-pod
spec:
  containers:
  - name: writer
    image: busybox
    command:
    - /bin/sh
    - -c
    - |
      while true; do
        echo "Writer: $(date)" >> /data/log.txt
        sleep 5
      done
    volumeMounts:
    - name: storage
      mountPath: /data
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: my-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: reader-pod
spec:
  containers:
  - name: reader
    image: busybox
    command:
    - /bin/sh
    - -c
    - |
      while true; do
        echo "=== Log Contents ==="
        cat /data/log.txt
        sleep 10
      done
    volumeMounts:
    - name: storage
      mountPath: /data
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: my-pvc