apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pov

spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Retain, Recycle, Delete 
  storageClassName: manual
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate