apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi # Request 500 MiB of storage ( less than PV's capacity of 1 GiB )
  storageClassName: manual